# Generated by Django 5.2.7 on 2025-11-05 04:05

import akademik.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('kaprodi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(max_length=100)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=10)),
                ('sks', models.PositiveSmallIntegerField()),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kuliah', to='akademik.prodi')),
            ],
            options={
                'unique_together': {('matkul', 'prodi', 'hari')},
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=akademik.models.siswa_photo_path)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa', to='akademik.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrasi', to='akademik.kuliah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrasi', to='akademik.siswa')),
            ],
            options={
                'unique_together': {('student', 'kuliah')},
            },
        ),
    ]
