# Generated by Django 5.2.7 on 2025-11-05 06:18

import berita.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, unique=True)),
                ('tanggal', models.DateField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=berita.models.berita_image_path)),
                ('isi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('isi', models.TextField()),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='berita.berita')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
