# Generated by Django 5.2.7 on 2025-11-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-tanggal']},
        ),
        migrations.RemoveField(
            model_name='berita',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='updated_at',
        ),
    ]
